### ISSUE TITLE
Not working in python3

### ISSUE THREAD

**Issue by zclandry** [PorkShoulderHolder/python-libmf#7]
The python interface errors when importing. It seems likely that it is due to the python2.7 formatted print statements. Error below:

File "", line 1, in
from libmf import mf

File "/usr/local/lib/python3.7/dist-packages/libmf/mf.py", line 78
print "Unrecognized keyword argument '{0}={1}'".format(kw, kwargs[kw])
^
SyntaxError: invalid syntax

**Comment by PorkShoulderHolder** [comment]
This has been fixed

**Comment by PorkShoulderHolder** [comment]
Fixed in version '0.9.2'

**Comment by PorkShoulderHolder** [comment]
fixed in `version 0.9.2`
